server:
  port: 8888
spring:
  mvc:
    view:
      prefix: /WEB-INF/
      suffix:  .html
  datasource:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/timu?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
      username: root
      password: root
mybatis:
  mapper-locations: classpath:com/home/dao/*Mapper.xml
  type-aliases-package: com.home.entity



